api:

ota:
  - platform: esphome
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: ${reboot_timeout}
  power_save_mode: none
  manual_ip:
    static_ip: ${static_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0
