substitutions:
  tx_pin: GPIO17
  rx_pin: GPIO16

esphome:
  name: bedroom-motion-sensor
  friendly_name: Bedroom Motion Sensor
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("");

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  baud_rate: 0

ota:
  - platform: esphome
    id: my_ota
    password: "3373716c7967d461cf4bd0ce1ba42e9a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout:
    minutes: 1
  manual_ip:
    static_ip: 192.168.0.231
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
    #ssid: "Ld2410-Esp32-5 Fallback Hotspot"
    #password: "AhxmD317i7r1"

esp32_ble_tracker:
  scan_parameters:
    continuous: true
    interval: 211ms
    window: 120ms
    active: True
  on_ble_service_data_advertise :
    - mac_address: 88:22:B2:F2:B3:E1
      service_uuid: 181B
      then:
        - lambda: |-
            uint32_t sum = 0;
            // Calculate the sum of the last 5 elements
            for (size_t i = x.size() > 5 ? x.size() - 5 : 0; i < x.size(); ++i) {
                sum += x[i];
            }
            if (sum != id(current_scale_reading).state)
            {
              id(current_scale_reading).publish_state(sum);
              id(mi_scale_occupancy).publish_state(true);
              ESP_LOGD("BLE","Mi Scale Occupied");
            }
            else
            {
              id(mi_scale_occupancy).publish_state(false);
            }

bluetooth_proxy:
  active: true

api:

light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    pin: GPIO2
    id: light_output

packages:
  sensor1: !include ld2410.base.yaml

sensor:

  - platform: template
    name: "Current Scale Reading"
    id: current_scale_reading

  - platform: xiaomi_miscale
    mac_address: 88:22:B2:F2:B3:E1
    weight:
      id: weight_miscale
      name: "Xiaomi Mi Scale Weight"
    impedance:
      name: "Xiaomi Mi Scale Impedance"
    clear_impedance: false

binary_sensor:

  - platform: template
    name: "Mi Scale Presence"
    id: mi_scale_occupancy
    device_class: occupancy

# remote_transmitter:
#   - carrier_duty_percent: 50%
#     pin: 15

# button:
#   - platform: template
#     name: "Projector Power"
#     icon: "mdi:power"
#     on_press:
#       then:
#         - remote_transmitter.transmit_raw:
#             carrier_frequency: 38kHz
#             code: [9044, -4542, 550, -1708, 552, -1708, 575, -559, 550, -1709, 551, -1709, 551, -1708, 550, -583, 551, -584, 550, -584, 575, -559, 549, -1710, 551, -563, 594, -559, 551, -583, 550, -1710, 550, -1710, 549, -585, 548, -585, 549, -564, 594, -560, 550, -585, 549, -584, 549, -586, 548, -586, 548, -1711, 572, -1687, 571, -1689, 547, -1710, 550, -1709, 574, -1687, 548, -1711, 572, -1686, 573]
#         - remote_transmitter.transmit_raw:
#             carrier_frequency: 38kHz
#             code: [9019, -2284, 572]
#   - platform: template
#     name: "Projector Power Off"
#     icon: "mdi:power-off"
#     on_press:
#       then:
#         - remote_transmitter.transmit_raw:
#             carrier_frequency: 38kHz
#             code: [9044, -4542, 550, -1708, 552, -1708, 575, -559, 550, -1709, 551, -1709, 551, -1708, 550, -583, 551, -584, 550, -584, 575, -559, 549, -1710, 551, -563, 594, -559, 551, -583, 550, -1710, 550, -1710, 549, -585, 548, -585, 549, -564, 594, -560, 550, -585, 549, -584, 549, -586, 548, -586, 548, -1711, 572, -1687, 571, -1689, 547, -1710, 550, -1709, 574, -1687, 548, -1711, 572, -1686, 573]
#         - remote_transmitter.transmit_raw:
#             carrier_frequency: 38kHz
#             code: [9019, -2284, 572]
#         - delay: 500ms
#         - remote_transmitter.transmit_raw:
#             carrier_frequency: 38kHz
#             code: [9044, -4542, 550, -1708, 552, -1708, 575, -559, 550, -1709, 551, -1709, 551, -1708, 550, -583, 551, -584, 550, -584, 575, -559, 549, -1710, 551, -563, 594, -559, 551, -583, 550, -1710, 550, -1710, 549, -585, 548, -585, 549, -564, 594, -560, 550, -585, 549, -584, 549, -586, 548, -586, 548, -1711, 572, -1687, 571, -1689, 547, -1710, 550, -1709, 574, -1687, 548, -1711, 572, -1686, 573]
#         - remote_transmitter.transmit_raw:
#             carrier_frequency: 38kHz
#             code: [9019, -2284, 572]
#   - platform: template
#     name: "Projector Volume+"
#     icon: "mdi:volume-plus"
#     on_press:
#       then:
#         remote_transmitter.transmit_nec:
#           address: 0xC43B
#           command: 0xF50A
#           command_repeats: 1
#   - platform: template
#     name: "Projector Volume-"
#     icon: "mdi:volume-minus"
#     on_press:
#       then:
#         remote_transmitter.transmit_nec:
#           address: 0xC43B
#           command: 0xF708
#           command_repeats: 1
