esphome:
  name: garbage-lid
  friendly_name: Garbage Lid
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: "esp32-c3-devkitm-1"
  variant: "ESP32C3"
  framework:
    type: "esp-idf"
    version: "recommended"

logger:
    level: INFO
packages:
  sensor1: !include ld2410.base.yaml

substitutions:
  tx_pin: GPIO21
  rx_pin: GPIO20

api:
ota:
  - platform: esphome
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout:
    minutes: 1
  manual_ip:
    static_ip: 192.168.0.111
    gateway: 192.168.0.1
    subnet: 255.255.255.0

servo:
  - id: servo_motor
    output: pwm_output

# Example output platform
# On ESP32, use ledc output
output:
  - platform: ledc
    id: pwm_output
    pin: GPIO4
    frequency: 50 Hz

number:
  - platform: template
    name: Servo Control
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_motor
            level: !lambda 'return x / 100.0;'
