esphome:
  name: sala-motion-sensor
  friendly_name: Sala Motion Sensor

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 5.4.1

logger:
  level: WARN
  baud_rate: 0

packages:
  presence: !include Common/ld2410.base.yaml
  connection: !include Common/connection.base.yaml
  ondevice_led: !include Common/ondevice-led.base.yaml

substitutions:
  tx_pin: RX
  rx_pin: TX
  static_ip: 192.168.0.220
  reboot_timeout: 1min

esp32_ble_tracker:
  scan_parameters:
    continuous: true
    interval: 211ms
    window: 120ms
    active: True

bluetooth_proxy:
  active: true