esphome:
  name: pantry-motion-sensor
  friendly_name: Pantry Motion Sensor
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("");

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: ERROR

ota:
  - platform: esphome
    password: "e922289d163bdafa65f7a97407f9d8bd"
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout:
    minutes: 1
  manual_ip:
    static_ip: 192.168.0.129
    gateway: 192.168.0.1
    subnet: 255.255.255.0

substitutions:
  tx_pin: GPIO7
  rx_pin: GPIO6
api:
packages:
  device_base: !include ld2410.base.yaml

# esp32_ble_tracker:
#   scan_parameters:
#     continuous: true
#     interval: 211ms
#     window: 120ms
#     active: True

# bluetooth_proxy:
#   active: true


# light:
#   - platform: esp32_rmt_led_strip
#     name: Status LED
#     pin: GPIO8
#     rgb_order: GRB
#     num_leds: 1
#     rmt_channel: 0
#     chipset: ws2812
#     entity_category: config
#     restore_mode: ALWAYS_OFF

# uart:
#   id: uart_bus
#   rx_pin:
#     number: GPIO6
#     mode:
#       input: true
#       pullup: true
#   tx_pin:
#     number: GPIO7
#     mode:
#       input: true
#       pullup: true
#   baud_rate: 256000
#   parity: NONE
#   stop_bits: 1
#   data_bits: 8