esphome:
  name: pantry-motion-sensor
  friendly_name: Pantry Motion Sensor

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended

logger:
  level: WARN

packages:
  presence: !include Common/ld2410.base.yaml
  connection: !include Common/connection.base.yaml
  ondevice-rgb: !include Common/ondevice-rgb.base.yaml

substitutions:
  tx_pin: GPIO7
  rx_pin: GPIO6
  static_ip: 192.168.0.129
  reboot_timeout: 1min