esphome:
  name: bathroom-motion-sensor
  friendly_name: Bathroom Motion Sensor

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: ERROR

ota:
  - platform: esphome
    password: "e922289d163bdafa65f7a97407f9d8bd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  reboot_timeout:
    minutes: 0
  power_save_mode: NONE
  output_power: 17dB
  manual_ip:
    static_ip: 192.168.0.80
    gateway: 192.168.0.1
    subnet: 255.255.255.0
api:

substitutions:
  tx_pin: GPIO7
  rx_pin: GPIO6

packages:
  device_base: !include ld2410.base.yaml