esphome:
  name: desk-motion-sensor
  friendly_name: Desk Motion Sensor
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("");

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: INFO

ota:
  - platform: esphome
    password: "e922289d163bdafa65f7a97407f9d8bd"
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout:
    minutes: 5
  manual_ip:
    static_ip: 192.168.0.75
    gateway: 192.168.0.1
    subnet: 255.255.255.0
api:
substitutions:
  tx_pin: GPIO7
  rx_pin: GPIO6

packages:
  device_base: !include ld2410.base.yaml

# esp32_ble_tracker:
#   scan_parameters:
#     continuous: true
#     interval: 211ms
#     window: 120ms
#     active: True

# bluetooth_proxy:
#   active: true

# remote_receiver:
#   - pin:
#       number: 8
#       inverted: true
#     dump: all
